name: Deploy to Local

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to local
        run: |
          # Add deployment commands specific to your project
          # For example:
           npm install
           npm start
